// All UI text in one place — swap this file to localize.
export const STR = {
  title: 'SkyRush FPV',
  subtitle: 'Browser FPV drone — no install, just fly',
  freeFlight: 'Free Flight',
  race: 'Race',
  settings: 'Settings',
  resume: 'Resume',
  restart: 'Restart',
  mainMenu: 'Main Menu',
  back: 'Back',
  raceFinished: 'Race Finished!',
  newBest: 'New best time!',
  best: 'Best',
  retry: 'Retry',
  crashed: 'CRASHED',
  go: 'GO!',
  gate: 'Gate',
  paused: 'Paused',
  // settings labels
  flightMode: 'Flight mode',
  angle: 'Angle (easy)',
  acro: 'Acro (pro)',
  sensitivity: 'Mouse sensitivity',
  fov: 'FOV',
  cameraTilt: 'Camera tilt',
  quality: 'Graphics quality',
  qLow: 'Low',
  qMedium: 'Medium',
  qHigh: 'High',
  volume: 'Volume',
  controlScheme: 'Controls',
  cAuto: 'Auto-detect',
  cDesktop: 'Keyboard + Mouse',
  cTouch: 'Touch sticks',
  helpDesktop:
    'W/S throttle · Mouse pitch & yaw · A/D roll · R reset · C camera · ESC menu',
  helpTouch: 'Left stick: throttle + yaw · Right stick: pitch + roll',
} as const;
